mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', include('polls.urls')),
    path('accounts/', include('allauth.urls')),
    path('unicorn/', include('django_unicorn.urls')),


]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('numberofpolls/', views.numberofpolls, name='numberofpolls'),
    path('numberofvotes/', views.numberofvotes, name='numberofvotes'),
    path('about/', views.about, name="about"),
    path('profile/', views.profile, name="profile"),
]

mysite/polls/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    question_description = models.CharField(max_length=500)
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from .decorators import group_required
from .models import Question, Choice

# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    if request.user.groups.filter(name='member').exists():
        ismember = True
    else:
        ismember = False

    context = {'latest_question_list': latest_question_list,
    'ismember': ismember}
    return render(request, 'polls/index.html', context)

@login_required(login_url='/accounts/login/')
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

@login_required(login_url='/accounts/login/')
def profile(request):
    
    if request.user.groups.filter(name='member').exists():
        ismember = True
    else:
        ismember = False
    context = {'ismember' : ismember}
    return render(request, 'polls/profile.html', context)

  
#@permission_required('polls.view_question', raise_exception=True)   
@login_required(login_url='/accounts/login/')
@group_required('member')    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
    
@login_required(login_url='/accounts/login/')
def vote(request, question_id):
    
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
        
            return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
        
            return render(request, 'polls/detail.html',{
                'votesuccess': "success",
            })
    

def numberofpolls(request):
    nq = Question.objects.count()
    return HttpResponse("%s" % nq)

def numberofvotes(request):
    result = 0
    cs = Choice.objects.all()
    for c in cs :
        result = result + c.votes
    
    return HttpResponse("%i" % result)

def about(request):
    return render(request, 'polls/about.html')

mysite/polls/templates/polls/about.html
{% extends "polls/base.html" %}

{% block content %}

<h2 class="text-center">About</h2>
<p></p>
</article>
<div class=" w-75 mx-auto card">
    
    <div class="card-body">
      <h5 class="card-title text-center">Who are we?</h5>
      <p class="card-text">This is the about page</p>
      
      
    </div>
  </div>
{% endblock %}

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<head>
    {% load static %}

     <!-- Import bootstrap 4 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Import full version of JQuerry for ajax-->
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
    
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <title>{% block title %}Polls Website{% endblock %}</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand">Polls</span>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:about' %}">About</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
        
          <li class="nav-item">
            <span class="nav-link">Welcome, <a href="{% url 'polls:profile' %}">{{ user.get_username }}</a></span>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/accounts/logout">Logout</a>
        </li>
        
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/accounts/signup">Register</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/accounts/login">Login</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <div class="content clearfix pb-5">
    {% block content %} {% endblock %}
    </div>

    <!-- Footer -->
<footer class="page-footer font-small unique-color-dark">

  

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3">

      
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        
        <h6 class="text-uppercase font-weight-bold">Number Of Polls</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <h1 id="numberofpolls">
        </h1>

      </div>
      

      
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Total Votes</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <h1 id="numberofvotes"></h1>

      </div>
      

      
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Useful Pages</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a href="{% url 'polls:index' %}">Home</a>
        </p>
        <p>
          <a href="{% url 'polls:about' %}">About</a>
        </p>
        
        

      </div>
    </div>
  </div>
  
  <div class="footer-copyright text-center py-3">© 2022 Copyright: <a href="https://www.swingit.be/">SwingIT</a>
  </div>

</footer>
<script>
  $.ajax({
    type: 'GET',
    url: 'http://localhost:8000/numberofpolls',
    dataType: 'text',
    success: function(res){
              //answer of api call.
              $("#numberofpolls").html(res);
            },
    error: function(error) {
        $("#numberofpolls").html("0");
    }
});

$.ajax({
    type: 'GET',
    url: 'http://localhost:8000/numberofvotes',
    dataType: 'text',
    success: function(res){
              //answer of api call.
              $("#numberofvotes").html(res);
            },
    error: function(error) {
        $("#numberofvotes").html("0");
    }
});

</script>

</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load unicorn%}
{% block content %}




{% unicorn 'vote' %}
    
    {% endblock %}

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% load unicorn%}

{% block content %}

{% unicorn 'pollsoverview' %}

{% endblock %}

mysite/polls/templates/polls/profile.html
{% extends "polls/base.html" %}
{% load static %}
{% block content %}

<h2 class="text-center">Profile</h2>
<p></p>
</article>


  <div class="card mb-3 mx-auto" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="{% static 'polls/images/profile.png' %}" alt="profile" width="125">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">Username:</h5>
          <p class="card-text">{{ user.get_username }}</p>
          <h5 class="card-title">Member status:</h5>
          {% if ismember %}
          <p class="card-text">Yes</small></p>
          {% else %}
          <p class="card-text">No</small></p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mysite/polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% load unicorn%}
{% block content %}

{% unicorn 'result' %}

{% endblock %}

mysite/polls/templates/unicorn/footer.html
<div>
    <!-- put component code here -->
    <footer class="page-footer font-small unique-color-dark">

      <button unicorn:click="get_updates">Update Footer</button>

        <!-- Footer Links -->
        <div class="container text-center text-md-left mt-5">
      
          <!-- Grid row -->
          <div class="row mt-3">
      
            
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
      
              
              <h6 class="text-uppercase font-weight-bold">Number Of Polls</h6>
              <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
              <h1>
                {{ nq }}
              </h1>
      
            </div>
            
      
            
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
      
              <!-- Links -->
              <h6 class="text-uppercase font-weight-bold">Total Votes</h6>
              <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
              <h1>{{ nv }}</h1>
              
            </div>
            
      
            
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
      
              <!-- Links -->
              <h6 class="text-uppercase font-weight-bold">Useful Pages</h6>
              <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
              <p>
                <a href="{% url 'polls:index' %}">Home</a>
              </p>
              <p>
                <a href="{% url 'polls:about' %}">About</a>
              </p>
              
              
      
            </div>
          </div>
        </div>
        
        <div class="footer-copyright text-center py-3">© 2022 Copyright: <a href="https://www.swingit.be/">SwingIT</a>
        </div>
      
      </footer>
      
</div>

mysite/polls/templates/unicorn/navbar.html
<div>
    <!-- put component code here -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand">Polls</span>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:about' %}">About</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
        
          <li class="nav-item">
            <span class="nav-link">Welcome, <a href="{% url 'polls:profile' %}">{{ user.get_username }}</a></span>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="/accounts/logout">Logout</a>
        </li>
        
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="/accounts/signup">Register</a>
      </li>
        <li class="nav-item">
            <a class="nav-link" href="/accounts/login">Login</a>
        </li>
        {% endif %}
      </ul>
    </nav>
</div>

mysite/polls/templates/unicorn/pollsoverview.html
<div>
    <!-- put component code here -->
    <h2 class="text-center">All available polls</h2>
{% if latest_question_list  %}
 
    {% for question in latest_question_list %}

    
    <div class="card text-center float-left w-25 mx-5 my-4">
        
        <div class="card-body">
          
          <h5 class="card-title">{{ question.question_text }}</h5>
          <p class="card-text">{{ question.question_description }}</p>
          {% if user.is_authenticated %}
          <a href="/polls/{{ question.id }}/?question_id={{ question.id }}" class="btn btn-primary">Vote!</a>
          {% if ismember %}
          <a href="{% url 'polls:results' question.id %}" class="btn btn-warning">View Results</a>
          {% endif %}
          {% else %}
          <a class="btn btn-secondary" href="/accounts/login">Please login to vote</a>
          {% endif %}
        </div>
        
      </div>

    {% endfor %}




{% else %}
<p>No polls are available.</p>
{% endif %}
</div>

mysite/polls/templates/unicorn/result.html
<div>
    <h2 class="text-center">Results</h2>
<div class="card text-center w-50 mx-auto">
    <div class="card-header">
        Poll Name: {{ question.question_text }}
      </div>
<ul class="list-group">
{% for choice in question.choice_set.all %}
    <li class="list-group-item">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:index' %}" class=" btn btn-primary w-25 mx-auto my-3">Go back to all polls</a>
</div>
</div>

mysite/polls/templates/unicorn/vote.html
<div>
  {% if user.is_authenticated %}
  
          {% if error_message %}
              <div class="alert alert-danger" role="alert">
              {{ error_message }}</div>
          {% endif %}
  {{ votesuccess }}
          {% if not votesuccess %}
  
  
          {% csrf_token %}
          <h2 class="text-center">{{ q.question_text }}</h2>
          <div class="card w-25 mx-auto pb-3">
          <fieldset>
              <legend><h5  class="text-center">Make your choice:</h5></legend>
  
              {% for choice in q.choice_set.all %}
              <div class="form-check">
                  <input type="radio" name="keuze" id="keuze" unicorn:model="which" value="{{ choice.id }}">
                  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
              </div>
              {% endfor %}
  
          </fieldset>
          <button unicorn:click="addVote" class="btn btn-primary w-25 mx-auto">Vote</button>
        </div>
  
  
      {% else %}
          <div class="alert alert-success" role="alert">
              Your vote was submitted succesfully!
            </div>
            <p class="text-center"><a href="{% url 'polls:index' %}" class=" btn btn-primary">Go back to all polls</a></p>
      {% endif%}
  
  {% else %}
      <script> window.location.replace("/accounts/login"); </script>
  {% endif %}
  </div>
  